class InvoiceItem {
  final String itemNo;
  final String description;
  final int quantity;
  final double unitPrice;
  final double total;

  InvoiceItem({
    required this.itemNo,
    required this.description,
    required this.quantity,
    required this.unitPrice,
    required this.total,
  });

  factory InvoiceItem.fromMap(Map<String, dynamic> data) {
    return InvoiceItem(
      itemNo: data['itemNo'] ?? '',
      description: data['description'] ?? '',
      quantity: data['quantity'] ?? 0,
      unitPrice: (data['unitPrice'] ?? 0.0).toDouble(),
      total: (data['total'] ?? 0.0).toDouble(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'itemNo': itemNo,
      'description': description,
      'quantity': quantity,
      'unitPrice': unitPrice,
      'total': total,
    };
  }
}

class InvoiceModel {
  final String id;
  final String companyId; // The seller
  final String invoiceNo; 
  final String? fbrInvoiceNo; // Generated by mock FBR service
  final DateTime date;
  final String invoiceType;
  
  // Buyer Info
  final String buyerBusinessName;
  final String buyerRegistrationNo;
  final String buyerProvince;
  
  // Items & Totals
  final List<InvoiceItem> items;
  final double subtotal;
  final double tax;
  final double total;
  
  // Status (Draft, Submitted, etc.)
  final String status;
  final String? qrCodeData;
  
  final DateTime createdAt;
  final DateTime updatedAt;

  InvoiceModel({
    required this.id,
    required this.companyId,
    required this.invoiceNo,
    this.fbrInvoiceNo,
    required this.date,
    required this.invoiceType,
    required this.buyerBusinessName,
    required this.buyerRegistrationNo,
    required this.buyerProvince,
    required this.items,
    required this.subtotal,
    required this.tax,
    required this.total,
    required this.status,
    this.qrCodeData,
    required this.createdAt,
    required this.updatedAt,
  });

  factory InvoiceModel.fromMap(Map<String, dynamic> data, String documentId) {
    return InvoiceModel(
      id: documentId,
      companyId: data['companyId'] ?? '',
      invoiceNo: data['invoiceNo'] ?? '',
      fbrInvoiceNo: data['fbrInvoiceNo'],
      date: data['date'] != null 
          ? (data['date'] as DateTime) 
          : DateTime.now(),
      invoiceType: data['invoiceType'] ?? 'Standard',
      buyerBusinessName: data['buyerBusinessName'] ?? '',
      buyerRegistrationNo: data['buyerRegistrationNo'] ?? '',
      buyerProvince: data['buyerProvince'] ?? '',
      items: (data['items'] as List<dynamic>? ?? [])
          .map((item) => InvoiceItem.fromMap(item as Map<String, dynamic>))
          .toList(),
      subtotal: (data['subtotal'] ?? 0.0).toDouble(),
      tax: (data['tax'] ?? 0.0).toDouble(),
      total: (data['total'] ?? 0.0).toDouble(),
      status: data['status'] ?? 'Draft',
      qrCodeData: data['qrCodeData'],
      createdAt: data['createdAt'] != null 
          ? (data['createdAt'] as DateTime) 
          : DateTime.now(),
      updatedAt: data['updatedAt'] != null 
          ? (data['updatedAt'] as DateTime) 
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'companyId': companyId,
      'invoiceNo': invoiceNo,
      'fbrInvoiceNo': fbrInvoiceNo,
      'date': date,
      'invoiceType': invoiceType,
      'buyerBusinessName': buyerBusinessName,
      'buyerRegistrationNo': buyerRegistrationNo,
      'buyerProvince': buyerProvince,
      'items': items.map((item) => item.toMap()).toList(),
      'subtotal': subtotal,
      'tax': tax,
      'total': total,
      'status': status,
      'qrCodeData': qrCodeData,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}
